/*=============================================================================
Business Process : TRIBEPAD
Module           : TRIBEPAD_HIREDCARERS_TO_RS
Owner            : Veej
Description      : Get Hired Carers from Tribepad and send to Roster Systems
Dependencies     : 
=============================================================================*/

CREATE OR REPLACE PROCEDURE BBC_SOURCE_RAW.TRIBEPAD.SP_TRIBEPAD_CARERS_HIRED()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_new_count    NUMBER         := 0;
    v_retry_count  NUMBER         := 0;
    v_result       STRING;
    v_sql          STRING;
BEGIN
    ----------------------------------------------------------------
    -- 1) Deduplicate source table via atomic SWAP (with safety check)
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TMP AS
    SELECT *
    FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY DATE_IN_STATUS_3, CANDIDATE_NAME_TITLE,
                     CANDIDATE_PROTECTED_NAME_FIRST, CANDIDATE_PROTECTED_NAME_LAST
        ORDER BY TRY_TO_TIMESTAMP(DATE_IN_STATUS_3, 'DD/MM/YYYY HH24:MI') DESC,
                 NVL(CANDIDATE_PROTECTED_EMAIL,'') DESC
    ) = 1;

    IF ((SELECT COUNT(*) FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TMP) > 0) THEN
        ALTER TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TMP
        SWAP WITH BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED;
    END IF;

    ----------------------------------------------------------------
    -- 2) Delta of NEW records since last SUCCESS
    ----------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE TMP_CARERS_HIRED_DELTA AS
    SELECT
        *,
        TRY_TO_TIMESTAMP(DATE_IN_STATUS_3, 'DD/MM/YYYY HH24:MI') AS DATE_IN_STATUS_3_TS
    FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED
    WHERE TRY_TO_TIMESTAMP(DATE_IN_STATUS_3, 'DD/MM/YYYY HH24:MI') >
          COALESCE(
              (SELECT MAX(MAX_DATE)::TIMESTAMP_NTZ
               FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING
               WHERE STATUS = 'SUCCESS'),
              TO_TIMESTAMP_NTZ('1900-01-01', 'YYYY-MM-DD')
          )
      AND TRY_TO_TIMESTAMP(DATE_IN_STATUS_3, 'DD/MM/YYYY HH24:MI') IS NOT NULL;

    SELECT COUNT(*) INTO v_new_count FROM TMP_CARERS_HIRED_DELTA;

    ----------------------------------------------------------------
    -- 3) HubSpot roster mapping
    ----------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE TMP_HUBCOM AS
    SELECT DISTINCT
           UPPER(TRIM(COMPANY_NAME)) AS COMPANY_NAME_UC,
           ROSTER_SYSTEM
    FROM BBC_SOURCE_RAW.HS_STRUTO.COMPANY_INFO_HUBSPOT;

    ----------------------------------------------------------------
    -- 4) Prepare UPSERT set for NEW records
    ----------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE TMP_UPSERT_SET AS
    SELECT
        h.ROSTER_SYSTEM,
        n.*,
        CURRENT_TIMESTAMP()           AS PROCESSED_TIMESTAMP,
        CAST(NULL AS TIMESTAMP_NTZ)   AS SENT_TIMESTAMP
    FROM TMP_CARERS_HIRED_DELTA n
    LEFT JOIN TMP_HUBCOM h
      ON UPPER(TRIM(n.HIERARCHY_NAME)) = h.COMPANY_NAME_UC;

    ----------------------------------------------------------------
    -- 5) RETRY candidates: previously NULL roster, now mappable
    ----------------------------------------------------------------
    CREATE OR REPLACE TEMPORARY TABLE TMP_RETRY_CANDIDATES AS
    SELECT
        h.ROSTER_SYSTEM,
        hist.* EXCLUDE (ROSTER_SYSTEM, PROCESSED_TIMESTAMP, SENT_TIMESTAMP),
        CURRENT_TIMESTAMP()   AS PROCESSED_TIMESTAMP,
        hist.SENT_TIMESTAMP   AS SENT_TIMESTAMP
    FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS hist
    LEFT JOIN TMP_HUBCOM h
      ON UPPER(TRIM(hist.HIERARCHY_NAME)) = h.COMPANY_NAME_UC
    WHERE hist.ROSTER_SYSTEM IS NULL
      AND h.ROSTER_SYSTEM IS NOT NULL;

    SELECT COUNT(*) INTO v_retry_count FROM TMP_RETRY_CANDIDATES;

    INSERT INTO TMP_UPSERT_SET
    SELECT * FROM TMP_RETRY_CANDIDATES;

    ----------------------------------------------------------------
    -- 6) Single MERGE for UPDATE + INSERT (atomic, clean)
    ----------------------------------------------------------------
    MERGE INTO BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS tgt
    USING TMP_UPSERT_SET src
    ON  tgt.CANDIDATE_PROTECTED_NAME_FIRST = src.CANDIDATE_PROTECTED_NAME_FIRST
    AND tgt.CANDIDATE_PROTECTED_NAME_LAST  = src.CANDIDATE_PROTECTED_NAME_LAST
    AND tgt.DATE_IN_STATUS_3               = src.DATE_IN_STATUS_3
    WHEN MATCHED THEN
      UPDATE SET
        ROSTER_SYSTEM        = src.ROSTER_SYSTEM,
        PROCESSED_TIMESTAMP  = src.PROCESSED_TIMESTAMP
    WHEN NOT MATCHED THEN
      INSERT (
        ROSTER_SYSTEM,
        CANDIDATE_NAME_TITLE,
        CANDIDATE_PROTECTED_NAME_FIRST,
        CANDIDATE_PROTECTED_NAME_LAST,
        CANDIDATE_PROTECTED_EMAIL,
        CANDIDATE_PROTECTED_TELEPHONE,
        CANDIDATE_PROTECTED_MOBILE,
        CANDIDATE_ADDRESS_FULL_COUNTRY,
        CANDIDATE_PROTECTED_POSTCODE,
        CANDIDATE_NATIONALITY,
        QUESTIONBANK_462_ANSWER,
        QUESTIONBANK_604_ANSWER,
        QUESTIONBANK_1030_ANSWER,
        QUESTIONBANK_1204_ANSWER,
        QUESTIONBANK_1205_ANSWER,
        HIERARCHY_NAME,
        _HIERARCHY_PATH,
        DATE_IN_STATUS_3,
        DATE_IN_STATUS_3_TS,
        PROCESSED_TIMESTAMP,
        SENT_TIMESTAMP,
        CANDIDATE_DOB
      )
      VALUES (
        src.ROSTER_SYSTEM,
        src.CANDIDATE_NAME_TITLE,
        src.CANDIDATE_PROTECTED_NAME_FIRST,
        src.CANDIDATE_PROTECTED_NAME_LAST,
        src.CANDIDATE_PROTECTED_EMAIL,
        src.CANDIDATE_PROTECTED_TELEPHONE,
        src.CANDIDATE_PROTECTED_MOBILE,
        src.CANDIDATE_ADDRESS_FULL_COUNTRY,
        src.CANDIDATE_PROTECTED_POSTCODE,
        src.CANDIDATE_NATIONALITY,
        src.QUESTIONBANK_462_ANSWER,
        src.QUESTIONBANK_604_ANSWER,
        src.QUESTIONBANK_1030_ANSWER,
        src.QUESTIONBANK_1204_ANSWER,
        src.QUESTIONBANK_1205_ANSWER,
        src.HIERARCHY_NAME,
        src._HIERARCHY_PATH,
        src.DATE_IN_STATUS_3,
        src.DATE_IN_STATUS_3_TS,
        src.PROCESSED_TIMESTAMP,
        src.SENT_TIMESTAMP,
        src.CANDIDATE_DOB
      );

    ----------------------------------------------------------------
    -- 7) Tracking (NEW + RETRY records)
    ----------------------------------------------------------------
    IF (v_new_count > 0) THEN
        INSERT INTO BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING (MAX_DATE, STATUS, RECORDS_PROCESSED)
        SELECT MAX(DATE_IN_STATUS_3_TS), 'SUCCESS', :v_new_count
        FROM TMP_CARERS_HIRED_DELTA;
    END IF;

    IF (v_retry_count > 0) THEN
        INSERT INTO BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING (MAX_DATE, STATUS, RECORDS_PROCESSED)
        SELECT CURRENT_TIMESTAMP(), 'RETRY', :v_retry_count;
    END IF;

    ----------------------------------------------------------------
    -- 8) Log success
    ----------------------------------------------------------------
    v_result := 'TRIBEPAD: SUCCESS. New: ' || TO_VARCHAR(v_new_count) || ', Retry: ' || TO_VARCHAR(v_retry_count) || ', Total: ' || TO_VARCHAR(v_new_count + v_retry_count) || ' processed.';

    v_sql := 'INSERT INTO BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS 
           (LOG_TIMESTAMP, TASK_NAME, RETURN_MESSAGE, STATUS)
         VALUES (
           CONVERT_TIMEZONE(''UTC'', ''Europe/London'', CURRENT_TIMESTAMP()),
           ''D04_TRIBEPAD_CARERS_HIRED'',
           ''' || REPLACE(v_result, '''', '''''') || ''',
           ''SUCCESS''
         )';
    EXECUTE IMMEDIATE v_sql;

    ----------------------------------------------------------------
    -- 9) Cleanup (TEMP tables auto-drop at session end, no explicit drop needed)
    ----------------------------------------------------------------

    RETURN v_result;

EXCEPTION
  WHEN OTHER THEN
  BEGIN
    v_result := 'TRIBEPAD: FAIL: ' || LEFT(SQLERRM, 250);

    v_sql := 'INSERT INTO BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS 
           (LOG_TIMESTAMP, TASK_NAME, RETURN_MESSAGE, STATUS)
         VALUES (
           CONVERT_TIMEZONE(''UTC'', ''Europe/London'', CURRENT_TIMESTAMP()),
           ''D04_TRIBEPAD_CARERS_HIRED'',
           ''' || REPLACE(v_result, '''', '''''') || ''',
           ''FAILURE''
         )';
    EXECUTE IMMEDIATE v_sql;

    -- Cleanup best-effort (TEMP tables auto-drop)

    RETURN v_result;
  END;
END;
$$;

-- Create or replace the task; minute hour day_of_month month day_of_week timezone
CREATE OR REPLACE TASK D04_TRIBEPAD_CARERS_HIRED
WAREHOUSE = REPORT_WH
SCHEDULE = 'USING CRON 55 8-18 * * 1-5 UTC'
AS
    CALL SP_TRIBEPAD_CARERS_HIRED();
    
--ALTER TASK D04_TRIBEPAD_CARERS_HIRED RESUME;
--SHOW TASKS;
/* CHECKS:
DESC TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED;
SELECT * FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS;
UPDATE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS 
SET SENT_TIMESTAMP = NULL
WHERE ROSTER_SYSTEM = 'One Touch Health' AND SENT_TIMESTAMP = '2025-09-09 08:50:07.556';

SELECT * FROM BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS ORDER BY LOG_TIMESTAMP DESC;
--DELETE FROM BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS WHERE TASK_NAME = 'D04_TRIBEPAD_CARERS_HIRED';
--DELETE FROM BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS WHERE LOG_TIMESTAMP < DATEADD(DAY, -3, CURRENT_DATE());

*/
    
/*------------------------------------------------------------------------------------------------
Send to OTH as csv file - only if there is data
*/
CREATE OR REPLACE PROCEDURE SP_TRIBEPAD_SENDTOOTH()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    filename STRING;
    sql_text STRING;
    v_count  NUMBER;
    v_result STRING;

BEGIN
    ALTER SESSION SET TIMEZONE = 'Europe/London';
    -- Count records that are ready to send
    SELECT COUNT(*) INTO v_count
    FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
    WHERE ROSTER_SYSTEM = 'One Touch Health'
      AND SENT_TIMESTAMP IS NULL;

    IF (v_count = 0) THEN
        RETURN 'TRIBEPAD: OTH: No new records since last run.';
    END IF;

    -- Build filename
    filename := 'CARERS_HIRED_' || TO_CHAR(CURRENT_TIMESTAMP(), 'YYYYMMDD_HH24MISS') || '.csv';

    -- Build COPY INTO command dynamically
    sql_text := '
        COPY INTO @EXTERNAL_INTEGRATIONS.BBC_TO_OTH.STG_BBC_TO_OTH_TRIBEPAD/' || filename || '
        FROM (
            SELECT
                CAST(CANDIDATE_NAME_TITLE AS STRING)               AS TITLE,
                CAST(CANDIDATE_PROTECTED_NAME_FIRST AS STRING)     AS NAME_FIRST,
                CAST(CANDIDATE_PROTECTED_NAME_LAST AS STRING)      AS NAME_LAST,
                CAST(CANDIDATE_DOB AS STRING)                      AS DOB,
                CAST(CANDIDATE_ADDRESS_FULL_COUNTRY AS STRING)     AS ADDRESS_FULL,
                CAST(CANDIDATE_PROTECTED_POSTCODE AS STRING)       AS POSTCODE,
                CAST(QUESTIONBANK_1205_ANSWER AS STRING)           AS AREA,
                CAST(CANDIDATE_PROTECTED_EMAIL AS STRING)          AS EMAIL,
                CAST(CANDIDATE_PROTECTED_TELEPHONE AS STRING)      AS TELEPHONE,
                CAST(CANDIDATE_PROTECTED_MOBILE AS STRING)         AS MOBILE,
                CAST(CANDIDATE_NATIONALITY AS STRING)              AS NATIONALITY,
                CAST(QUESTIONBANK_462_ANSWER AS STRING)            AS GENDER,
                CAST(QUESTIONBANK_1030_ANSWER AS STRING)           AS POSITION,
                CAST(QUESTIONBANK_604_ANSWER AS STRING)            AS NI_NUMBER,
                CAST(QUESTIONBANK_1204_ANSWER AS STRING)           AS TRANSPORT_TYPE,
                CAST(HIERARCHY_NAME AS STRING)                     AS OFFICE_LOCATION
            FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
            WHERE ROSTER_SYSTEM = ''One Touch Health''
              AND SENT_TIMESTAMP IS NULL
              --AND APP_CURRENT_PROCESSING_STATUS_OVERALL = ''Hired''
        )
        FILE_FORMAT = (TYPE = ''CSV'', FIELD_OPTIONALLY_ENCLOSED_BY = ''"'', COMPRESSION = ''NONE'')
        HEADER = TRUE
        SINGLE = TRUE;
    ';

    -- Execute COPY INTO [[Comment to Test]]
    EXECUTE IMMEDIATE sql_text; 

    -- Mark records as sent
    UPDATE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
        SET SENT_TIMESTAMP = CURRENT_TIMESTAMP()
        WHERE ROSTER_SYSTEM = 'One Touch Health'
          AND SENT_TIMESTAMP IS NULL;

    ----------------------------------------------------------------
    -- Log entries
    ----------------------------------------------------------------
    v_result := 'TRIBEPAD: OTH: Sent ' || v_count || ' records in ' || filename;

    EXECUTE IMMEDIATE
        'INSERT INTO BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS 
           (LOG_TIMESTAMP, TASK_NAME, RETURN_MESSAGE, STATUS)
         VALUES (
           CONVERT_TIMEZONE(''UTC'', ''Europe/London'', CURRENT_TIMESTAMP()),
           ''D04_TRIBEPAD_SENDTOOTH'',
           ''' || REPLACE(v_result, '''', '''''') || ''',
           ''SUCCESS''
         )';
    RETURN v_result;

EXCEPTION
  WHEN OTHER THEN
    v_result := 'TRIBEPAD: OTH: FAIL: ' || LEFT(SQLERRM, 250);

    EXECUTE IMMEDIATE
        'INSERT INTO BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS 
           (LOG_TIMESTAMP, TASK_NAME, RETURN_MESSAGE, STATUS)
         VALUES (
           CONVERT_TIMEZONE(''UTC'', ''Europe/London'', CURRENT_TIMESTAMP()),
           ''D04_TRIBEPAD_SENDTOOTH'',
           ''' || REPLACE(v_result, '''', '''''') || ''',
           ''FAILURE''
         )';
    RETURN v_result;
END;
$$;

CREATE OR REPLACE TASK D04_TRIBEPAD_SENDTOOTH
WAREHOUSE = REPORT_WH
AFTER D04_TRIBEPAD_CARERS_HIRED
AS
    CALL SP_TRIBEPAD_SENDTOOTH();
/*
SELECT * FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS WHERE ROSTER_SYSTEM = 'One Touch Health' AND SENT_TIMESTAMP IS NULL;
*/

/*------------------------------------------------------------------------------------------------
Send to PASS - only if there is data
*/
CREATE OR REPLACE PROCEDURE SP_TRIBEPAD_SENDTOPASS()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    v_count  NUMBER;
    v_result STRING;
BEGIN
    -- Ensure timestamps are UTC
    ALTER SESSION SET TIMEZONE = 'Europe/London';

    -- Count records that are ready to send
    SELECT COUNT(*) 
    INTO :v_count -- Use a colon to assign the result to the variable
    FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
    WHERE ROSTER_SYSTEM = 'Everylife PASS'
      AND SENT_TIMESTAMP IS NULL;

    -- Exit early if no records
    IF (:v_count = 0) THEN
        RETURN 'TRIBEPAD: PASS: NO NEW RECORDS SINCE LAST RUN';
    END IF;

    -- Insert into PASS output table with current UTC timestamp
    INSERT INTO BBCF_SFSHARE_OUT.PASS.TRIBEPAD_CARERS_HIRED (
        TITLE,
        NAME_FIRST,
        NAME_LAST,
        DOB,
        ADDRESS_FULL,
        POSTCODE,
        AREA,
        EMAIL,
        TELEPHONE,
        MOBILE,
        NATIONALITY,
        GENDER,
        POSITION,
        NI_NUMBER,
        TRANSPORT_TYPE,
        OFFICE_LOCATION,
        SENT_TIMESTAMP
    )
    SELECT
        CAST(CANDIDATE_NAME_TITLE AS STRING),
        CAST(CANDIDATE_PROTECTED_NAME_FIRST AS STRING),
        CAST(CANDIDATE_PROTECTED_NAME_LAST AS STRING),
        CAST(CANDIDATE_DOB AS STRING),
        CAST(CANDIDATE_ADDRESS_FULL_COUNTRY AS STRING),
        CAST(CANDIDATE_PROTECTED_POSTCODE AS STRING),
        CAST(QUESTIONBANK_1205_ANSWER AS STRING),
        CAST(CANDIDATE_PROTECTED_EMAIL AS STRING),
        CAST(CANDIDATE_PROTECTED_TELEPHONE AS STRING),
        CAST(CANDIDATE_PROTECTED_MOBILE AS STRING),
        CAST(CANDIDATE_NATIONALITY AS STRING),
        CAST(QUESTIONBANK_462_ANSWER AS STRING),
        CAST(QUESTIONBANK_1030_ANSWER AS STRING),
        CAST(QUESTIONBANK_604_ANSWER AS STRING),
        CAST(QUESTIONBANK_1204_ANSWER AS STRING),
        CAST(HIERARCHY_NAME AS STRING),
        CURRENT_TIMESTAMP()
    FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
    WHERE ROSTER_SYSTEM = 'Everylife PASS'
      AND SENT_TIMESTAMP IS NULL;

    -- Mark records as sent in the source table
    UPDATE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
        SET SENT_TIMESTAMP = CURRENT_TIMESTAMP()
        WHERE ROSTER_SYSTEM = 'Everylife PASS'
          AND SENT_TIMESTAMP IS NULL;

    ----------------------------------------------------------------
    -- Log entries
    ----------------------------------------------------------------
    v_result := 'TRIBEPAD: PASS: Sent ' || v_count || ' records.';

    EXECUTE IMMEDIATE
        'INSERT INTO BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS 
           (LOG_TIMESTAMP, TASK_NAME, RETURN_MESSAGE, STATUS)
         VALUES (
           CONVERT_TIMEZONE(''UTC'', ''Europe/London'', CURRENT_TIMESTAMP()),
           ''D04_TRIBEPAD_SENDTOPASS'',
           ''' || REPLACE(v_result, '''', '''''') || ''',
           ''SUCCESS''
         )';
    RETURN v_result;

EXCEPTION
  WHEN OTHER THEN
    v_result := 'TRIBEPAD: PASS: FAIL: ' || LEFT(SQLERRM, 250);

    EXECUTE IMMEDIATE
        'INSERT INTO BBC_SOURCE_RAW.HS_STRUTO.TASK_LOGS 
           (LOG_TIMESTAMP, TASK_NAME, RETURN_MESSAGE, STATUS)
         VALUES (
           CONVERT_TIMEZONE(''UTC'', ''Europe/London'', CURRENT_TIMESTAMP()),
           ''D04_TRIBEPAD_SENDTOPASS'',
           ''' || REPLACE(v_result, '''', '''''') || ''',
           ''FAILURE''
         )';
    RETURN v_result;
END;
$$;

CREATE OR REPLACE TASK D04_TRIBEPAD_SENDTOPASS
WAREHOUSE = REPORT_WH
AFTER D04_TRIBEPAD_CARERS_HIRED
AS
    CALL SP_TRIBEPAD_SENDTOPASS();

/*
SELECT * FROM BBCF_SFSHARE_OUT.PASS.TRIBEPAD_CARERS_HIRED ;
--DELETE FROM BBCF_SFSHARE_OUT.PASS.TRIBEPAD_CARERS_HIRED ;
SELECT * FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS WHERE ROSTER_SYSTEM = 'Everylife PASS'  
AND SENT_TIMESTAMP IS NULL;
*/
/*END***********************************************************/

/*
SHOW TASKS;
ALTER TASK D04_TRIBEPAD_CARERS_HIRED SUSPEND; -- ROOT TASK
ALTER TASK D04_TRIBEPAD_SENDTOOTH RESUME;
ALTER TASK D04_TRIBEPAD_SENDTOPASS RESUME;
ALTER TASK D04_TRIBEPAD_CARERS_HIRED RESUME;
SHOW TASKS;
*/

/* CHECKS:
SELECT * FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED;
SELECT * FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_DELTA_RS;

DESC TABLE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS;
SELECT * FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING;
-- DELETE FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING; --DAY1
-- DELETE FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS;

*/

/* DDL:
create or replace TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED (
	--APP_CURRENT_PROCESSING_STATUS_OVERALL VARCHAR(16777216),
	CANDIDATE_NAME_TITLE VARCHAR(16777216),
	CANDIDATE_PROTECTED_NAME_FIRST VARCHAR(16777216),
	CANDIDATE_PROTECTED_NAME_LAST VARCHAR(16777216),
	--CANDIDATE_NAME_FULL VARCHAR(16777216),
	CANDIDATE_PROTECTED_EMAIL VARCHAR(16777216),
	CANDIDATE_PROTECTED_TELEPHONE VARCHAR(16777216),
	CANDIDATE_PROTECTED_MOBILE VARCHAR(16777216),
	CANDIDATE_ADDRESS_FULL_COUNTRY VARCHAR(16777216),
	--CANDIDATE_PROTECTED_ADDRESS_1 VARCHAR(16777216),
	--CANDIDATE_PROTECTED_ADDRESS_2 VARCHAR(16777216),
	CANDIDATE_PROTECTED_POSTCODE VARCHAR(16777216),
	--CANDIDATE_PROTECTED_CITY VARCHAR(16777216),
	--CNDIDATE_PROTECTED_COUNTRY VARCHAR(16777216),
	CANDIDATE_DOB DATE,
	CANDIDATE_NATIONALITY VARCHAR(16777216),
	--CANDIDATE_RELOCATE_DISTANCE NUMBER(10,0),
	QUESTIONBANK_462_ANSWER VARCHAR(16777216),
	QUESTIONBANK_604_ANSWER VARCHAR(16777216),
	QUESTIONBANK_1030_ANSWER VARCHAR(16777CREATE OR REPLACE PROCEDURE SP_TRIBEPAD_SENDTOOTH()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS
	QUESTIONBANK_1204_ANSWER VARCHAR(16777216),
	QUESTIONBANK_1205_ANSWER VARCHAR(16777216),
	--JOB_COST_CENTRE VARCHAR(16777216),
	hierarchy_name VARCHAR(16777216),
	_hierarchy_path VARCHAR(16777216),
    date_in_status_3 VARCHAR(16777216)
);
ALTER TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED ALTER COLUMN CANDIDATE_DOB SET DATA TYPE VARCHAR;

DESC TABLE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS;
ALTER TABLE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS ADD COLUMN CANDIDATE_DOB_STR VARCHAR;
UPDATE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
SET CANDIDATE_DOB_STR = TO_VARCHAR(CANDIDATE_DOB, 'DD/MM/YYYY');  -- or your preferred format
ALTER TABLE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS DROP COLUMN CANDIDATE_DOB;
ALTER TABLE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS RENAME COLUMN CANDIDATE_DOB_STR TO CANDIDATE_DOB;

SELECT * FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED;
--DELETE FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED ;
--UPDATE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED SET hierarchy_name = 'Waterlooville'

SELECT * FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS;
DROP TABLE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS;
CREATE TABLE BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS AS
    SELECT * FROM BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_DELTA_RS;
DELETE FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS;


-- Create or update the tracking table with all required columns
CREATE OR REPLACE TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING (
    TRACKING_ID NUMBER IDENTITY(1,1),  -- Auto-increment ID for unique identification
    MAX_DATE TIMESTAMP_NTZ,             -- Maximum date processed in this batch
    STATUS VARCHAR(500),                -- Status: SUCCESS, PENDING, FAIL, NO_NEW_RECORDS
    RECORDS_PROCESSED NUMBER,           -- Count of records processed in this batch
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),  -- When this entry was created
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),  -- When this entry was last updated
    CONSTRAINT PK_CARERS_HIRED_TRACKING PRIMARY KEY (TRACKING_ID)
);

-- If the table already exists but is missing columns, add them:
-- ALTER TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING ADD COLUMN IF NOT EXISTS TRACKING_ID NUMBER IDENTITY(1,1);
-- ALTER TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING ADD COLUMN IF NOT EXISTS RECORDS_PROCESSED NUMBER;
-- ALTER TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING ADD COLUMN IF NOT EXISTS CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
-- ALTER TABLE BBC_SOURCE_RAW.TRIBEPAD.CARERS_HIRED_TRACKING ADD COLUMN IF NOT EXISTS UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();
);
*/

/*


create or replace table BBCF_SFSHARE_OUT.PASS.TRIBEPAD_CARERS_HIRED 
AS
            SELECT
                CAST(CANDIDATE_NAME_TITLE AS STRING)               AS TITLE,
                CAST(CANDIDATE_PROTECTED_NAME_FIRST AS STRING)     AS NAME_FIRST,
                CAST(CANDIDATE_PROTECTED_NAME_LAST AS STRING)      AS NAME_LAST,
                CAST(CANDIDATE_DOB AS STRING)                      AS DOB,
                CAST(CANDIDATE_ADDRESS_FULL_COUNTRY AS STRING)     AS ADDRESS_FULL,
                CAST(CANDIDATE_PROTECTED_POSTCODE AS STRING)       AS POSTCODE,
                CAST(QUESTIONBANK_1205_ANSWER AS STRING)           AS AREA,
                CAST(CANDIDATE_PROTECTED_EMAIL AS STRING)          AS EMAIL,
                CAST(CANDIDATE_PROTECTED_TELEPHONE AS STRING)      AS TELEPHONE,
                CAST(CANDIDATE_PROTECTED_MOBILE AS STRING)         AS MOBILE,
                CAST(CANDIDATE_NATIONALITY AS STRING)              AS NATIONALITY,
                CAST(QUESTIONBANK_462_ANSWER AS STRING)            AS GENDER,
                CAST(QUESTIONBANK_1030_ANSWER AS STRING)           AS POSITION,
                CAST(QUESTIONBANK_604_ANSWER AS STRING)            AS NI_NUMBER,
                CAST(QUESTIONBANK_1204_ANSWER AS STRING)           AS TRANSPORT_TYPE,
                CAST(HIERARCHY_NAME AS STRING)                     AS OFFICE_LOCATION,
                CAST(SENT_TIMESTAMP AS STRING)                    AS SENT_TIMESTAMP
            FROM BBC_DWH_DEV.SEMANTICMODEL.TRIBEPAD_CARERS_HIRED_RS
               WHERE ROSTER_SYSTEM = 'Everylife xPASS'
*/